### ISSUE TITLE
Index Error on item

### ISSUE THREAD

**Issue by kab11d** [Ethck/Path-of-Accounting#190] opened 2020-03-29 12:44 UTC
Didn't see a similar issue after searching...

Error: https://imgur.com/a/kF7ZgvF

Rarity: Unique
The Rippling Thoughts
Legion Sword
--------
One Handed Sword
Physical Damage: 134-248 (augmented)
Elemental Damage: 1-63 (augmented)
Critical Strike Chance: 5.00%
Attacks per Second: 1.20
Weapon Range: 11
--------
Requirements:
Level: 62
Str: 122
Dex: 104
--------
Sockets: R-R-G 
--------
Item Level: 81
--------
40% increased Global Accuracy Rating (implicit)
--------
Grants Summon Harbinger of the Arcane Skill
Trigger Level 20 Storm Cascade when you Attack
78% increased Spell Damage
153% increased Physical Damage
Adds 1 to 63 Lightning Damage
Adds 1 to 64 Lightning Damage to Spells
10% increased Area of Effect
--------

**Comment by rhzk** [comment] 2020-03-29 17:24
I am unable to reproduce the issue. Does it happens if you try the item again?
Maybe the text did not get properly copied the first time

**Comment by rhzk** [comment] 2020-03-29 17:53
Hi, Thanks for the report. Should be fixed in the next release

**Comment by kab11d** [comment] 2020-03-30 18:53
I tried the same item 4 times with mix of other items in between, I'll see
about buying one back and testing it again when I am off work. This was in
the newest release version as well.

**Comment by rhzk** [comment] 2020-03-30 18:58
Hi, the item had some empty lines on the end that didn't show up properly here on github
thats causing the bug you see:

```
Rarity: Unique
The Rippling Thoughts
Legion Sword
--------
One Handed Sword
Quality: +20% (augmented)
Physical Damage: 143-265 (augmented)
Elemental Damage: 1-67 (augmented)
Critical Strike Chance: 5.00%
Attacks per Second: 1.20
Weapon Range: 11
--------
Requirements:
Level: 62
Str: 122
Dex: 104
--------
Sockets: R-G-G 
--------
Item Level: 79
--------
40% increased Global Accuracy Rating (implicit)
--------
Grants Summon Harbinger of the Arcane Skill
Trigger Level 20 Storm Cascade when you Attack
77% increased Spell Damage
150% increased Physical Damage
Adds 1 to 67 Lightning Damage
Adds 1 to 61 Lightning Damage to Spells
10% increased Area of Effect
--------
       
       
       
     

```

It should be fixed in the next release (not out yet but soon)

**Closed as completed** 2020-03-31 17:13 UTC
Labels: Fixed-in-Dev
